/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nisum' at '1/19/17 11:45 PM' with Gradle 2.14.1
 *
 * @author nisum, @date 1/19/17 11:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
